[toolchain]
package_manager = "npm"

[features]
resolution = true
seeds = false
skip-lint = false

[programs.localnet]
solvent = "AuXUBafybLucgxw65twLs4RrwDnXDnxnfQxRrzamiDpq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json" # Use the standard WSL path

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
