[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solvent = "AuXUBafybLucgxw65twLs4RrwDnXDnxnfQxRrzamiDpq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/keewe/solvent-dev-wallet.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
